### ISSUE TITLE
运行semeval数据集时报错

### ISSUE THREAD

**Issue by charmerphil** [cuhksz-nlp/RE-AGCN#11]
在windows系统下运行本程序，通过pycharm传递参数。
运行sample无误，但是通过preprocess_dependency.py文件完成对semeval数据集的处理。随后运行re_agcn_main.py文件。在运行convert_examples_to_features方法时，第二次循环会报错。具体如下：
Traceback (most recent call last):
  File "F:/undergranduate/NLP/relation extraction/RE-AGCN/RE-AGCN-main/re_agcn_main.py", line 436, in <module>
    main()
  File "F:/undergranduate/NLP/relation extraction/RE-AGCN/RE-AGCN-main/re_agcn_main.py", line 429, in main
    train_func(args)
  File "F:/undergranduate/NLP/relation extraction/RE-AGCN/RE-AGCN-main/re_agcn_main.py", line 405, in train_func
    train(args, model, tokenizer, processor, device, args.n_gpu)
  File "F:/undergranduate/NLP/relation extraction/RE-AGCN/RE-AGCN-main/re_agcn_main.py", line 123, in train
    train_data = processor.build_dataset(train_examples, tokenizer, args.max_seq_length, "train", args)
  File "F:\undergranduate\NLP\relation extraction\RE-AGCN\RE-AGCN-main\data_utils.py", line 335, in build_dataset
    features = self.convert_examples_to_features(examples, tokenizer, max_seq_length)
  File "F:\undergranduate\NLP\relation extraction\RE-AGCN\RE-AGCN-main\data_utils.py", line 302, in convert_examples_to_features
    label_id = label_map[example["label"]]
KeyError: 'Other'
并未更改程序内任何部分。python为3.7.10，pytorch为1.8.0。希望能够获得回答。谢谢。

**Comment by charmerphil** [comment]
实测，报错为，label中的other中的“o”为小写，但是所产生的标签为Other，为大写“O”，因此无法匹配造成报错。

**Comment by charmerphil** [comment]
实测，报错原因为标签不完全一致，具体为other的首字母大小写区别。preprocess_dependency.py文件处理semeval数据时所产生的label.json文件中的other中的“o”为小写，但是程序运行过程中所产生的标签为Other，为大写“O”，因此无法匹配造成报错。

**Comment by douyameiyingyang** [comment]
请问下，在处理semeval数据集时，您有自己生成.tsv文件吗？

**Comment by charmerphil** [comment]
> 请问下，在处理semeval数据集时，您有自己生成.tsv文件吗？

没有生成tsv文件。改了一下preprocess_dependency.py文件里的就可以跑通。另外此程序运行时需要dev参与，但是semeval并不提供dev。

**Comment by douyameiyingyang** [comment]
那关于dev这块，您是怎么处理的啊？我试着只使用train和test发现代码中途会报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月10日(周二) 晚上10:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuhksz-nlp/RE-AGCN] 运行semeval数据集时报错 (Issue #11)




  
请问下，在处理semeval数据集时，您有自己生成.tsv文件吗？
  
没有生成tsv文件。改了一下preprocess_dependency.py文件里的就可以跑通。另外此程序运行时需要dev参与，但是semeval并不提供dev。

**Comment by charmerphil** [comment]
> 

截取了train中的一部分数据集充当dev

**Comment by douyameiyingyang** [comment]
好的，我试试。我在通过stanfordcorenlp进行标注的时候也出现了问题，标注超过1000个样本后，代码也会报错，说是json.decodeError。您有遇到这个情况吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月10日(周二) 晚上10:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuhksz-nlp/RE-AGCN] 运行semeval数据集时报错 (Issue #11)




   
截取了train中的一部分数据集充当dev

**Comment by charmerphil** [comment]
> 

并未遇到该问题，可查看是否使用了与源代码中所需要的工具版本相同。

**Comment by douyameiyingyang** [comment]
非常感谢您！大晚上的打扰您了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月10日(周二) 晚上10:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuhksz-nlp/RE-AGCN] 运行semeval数据集时报错 (Issue #11)




 
3.9.2

**Comment by douyameiyingyang** [comment]
您好，原论文使用的指标函数也是正确的，是我使用方法不对，这里也谢谢您的答复！

发件人: ***@***.***&gt;
发送时间: 2022年5月12日(周四) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuhksz-nlp/RE-AGCN] 运行semeval数据集时报错 (Issue #11)




 
重写了指标函数

**Comment by hhn0724** [comment]
> 我复现后的P,R,F1都为0，请问里面有什么讲究吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年5月10日(周二) 晚上10:37 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [cuhksz-nlp/RE-AGCN] 运行semeval数据集时报错 (Issue #11) 3.9.2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好，请问解决了吗？我重写指标函数后训练，第一个epoch之后几十个epochF值一直是0.16没变

**Comment by hhn0724** [comment]
> > 
> 
> 并未遇到该问题，可查看是否使用了与源代码中所需要的工具版本相同。
您好，请问您在semeval上训练结果怎么样啊？我调通代码后，训练20个epoch，从第一个epoch后，F值一直没变，一直0.16

**Comment by hhn0724** [comment]
> 您好，原论文使用的指标函数也是正确的，是我使用方法不对，这里也谢谢您的答复！ 发件人: ***@***.***&gt; 发送时间: 2022年5月12日(周四) 晚上10:01 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [cuhksz-nlp/RE-AGCN] 运行semeval数据集时报错 (Issue #11) 重写了指标函数 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
那请问您是怎么解决的？我这指标也是0.

**Comment by charmerphil** [comment]
您的邮件已经收到！杜卡泽重庆大学 机械与运载工程学院

**Comment by douyameiyingyang** [comment]
请问下，您重写的指标函数能分享给我吗？谢谢您！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月12日(周四) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuhksz-nlp/RE-AGCN] 运行semeval数据集时报错 (Issue #11)




 
重写了指标函数

**Comment by douyameiyingyang** [comment]
指标我没有动过



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月12日(周四) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cuhksz-nlp/RE-AGCN] 运行semeval数据集时报错 (Issue #11)




 
重写了指标函数
